package com.longan.biz.dataobject;

public class OperationRoleRelation {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column operation_role_relation.id
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	private Integer id;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column operation_role_relation.role_id
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	private Integer roleId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column operation_role_relation.operation_id
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	private Integer operationId;
	private String haveOperation;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column operation_role_relation.id
	 * 
	 * @return the value of operation_role_relation.id
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column operation_role_relation.id
	 * 
	 * @param id
	 *            the value for operation_role_relation.id
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column operation_role_relation.role_id
	 * 
	 * @return the value of operation_role_relation.role_id
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column operation_role_relation.role_id
	 * 
	 * @param roleId
	 *            the value for operation_role_relation.role_id
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column operation_role_relation.operation_id
	 * 
	 * @return the value of operation_role_relation.operation_id
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	public Integer getOperationId() {
		return operationId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column operation_role_relation.operation_id
	 * 
	 * @param operationId
	 *            the value for operation_role_relation.operation_id
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	public void setOperationId(Integer operationId) {
		this.operationId = operationId;
	}

	public String getHaveOperation() {
		return haveOperation;
	}

	public void setHaveOperation(String haveOperation) {
		this.haveOperation = haveOperation;
	}

}