package com.longan.biz.dataobject;

import java.util.Date;

public class OrderLog {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column order_log.id
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private Long id;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column order_log.biz_order_id
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private Long bizOrderId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column order_log.oper_id
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private Integer operId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column order_log.oper_name
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private String operName;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column order_log.gmt_create
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private Date gmtCreate;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column order_log.gmt_modify
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private Date gmtModify;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column order_log.error_code
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private String errorCode;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column order_log.error_msg
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private String errorMsg;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column order_log.log_type
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private Integer logType;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column order_log.memo
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private String memo;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column order_log.id
	 * 
	 * @return the value of order_log.id
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column order_log.id
	 * 
	 * @param id
	 *            the value for order_log.id
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column order_log.biz_order_id
	 * 
	 * @return the value of order_log.biz_order_id
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public Long getBizOrderId() {
		return bizOrderId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column order_log.biz_order_id
	 * 
	 * @param bizOrderId
	 *            the value for order_log.biz_order_id
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setBizOrderId(Long bizOrderId) {
		this.bizOrderId = bizOrderId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column order_log.oper_id
	 * 
	 * @return the value of order_log.oper_id
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public Integer getOperId() {
		return operId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column order_log.oper_id
	 * 
	 * @param operId
	 *            the value for order_log.oper_id
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setOperId(Integer operId) {
		this.operId = operId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column order_log.oper_name
	 * 
	 * @return the value of order_log.oper_name
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public String getOperName() {
		return operName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column order_log.oper_name
	 * 
	 * @param operName
	 *            the value for order_log.oper_name
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setOperName(String operName) {
		this.operName = operName;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column order_log.gmt_create
	 * 
	 * @return the value of order_log.gmt_create
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column order_log.gmt_create
	 * 
	 * @param gmtCreate
	 *            the value for order_log.gmt_create
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column order_log.gmt_modify
	 * 
	 * @return the value of order_log.gmt_modify
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public Date getGmtModify() {
		return gmtModify;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column order_log.gmt_modify
	 * 
	 * @param gmtModify
	 *            the value for order_log.gmt_modify
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setGmtModify(Date gmtModify) {
		this.gmtModify = gmtModify;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column order_log.error_code
	 * 
	 * @return the value of order_log.error_code
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public String getErrorCode() {
		return errorCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column order_log.error_code
	 * 
	 * @param errorCode
	 *            the value for order_log.error_code
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setErrorCode(String errorCode) {
		this.errorCode = errorCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column order_log.error_msg
	 * 
	 * @return the value of order_log.error_msg
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public String getErrorMsg() {
		return errorMsg;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column order_log.error_msg
	 * 
	 * @param errorMsg
	 *            the value for order_log.error_msg
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setErrorMsg(String errorMsg) {
		this.errorMsg = errorMsg;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column order_log.log_type
	 * 
	 * @return the value of order_log.log_type
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public Integer getLogType() {
		return logType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column order_log.log_type
	 * 
	 * @param logType
	 *            the value for order_log.log_type
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setLogType(Integer logType) {
		this.logType = logType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column order_log.memo
	 * 
	 * @return the value of order_log.memo
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column order_log.memo
	 * 
	 * @param memo
	 *            the value for order_log.memo
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}
}