package com.longan.biz.dataobject;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Map;

public class OrderLogExample {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table order_log
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	protected String orderByClause;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database table order_log
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table order_log
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public OrderLogExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table order_log
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	protected OrderLogExample(OrderLogExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table order_log
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table order_log
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table order_log
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table order_log
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table order_log
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table order_log
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method corresponds
	 * to the database table order_log
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Abator for iBATIS. This class corresponds to
	 * the database table order_log
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;

		protected List criteriaWithSingleValue;

		protected List criteriaWithListValue;

		protected List criteriaWithBetweenValue;

		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}

		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}

		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}

		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}

		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}

		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}

		protected void addCriterion(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}

		protected void addCriterionForJDBCDate(String condition, Date value, String property) {
			addCriterion(condition, new java.sql.Date(value.getTime()), property);
		}

		protected void addCriterionForJDBCDate(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List dateList = new ArrayList();
			Iterator iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(((Date) iter.next()).getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1, Date value2,
				String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return this;
		}

		public Criteria andIdIn(List values) {
			addCriterion("id in", values, "id");
			return this;
		}

		public Criteria andIdNotIn(List values) {
			addCriterion("id not in", values, "id");
			return this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return this;
		}

		public Criteria andBizOrderIdIsNull() {
			addCriterion("biz_order_id is null");
			return this;
		}

		public Criteria andBizOrderIdIsNotNull() {
			addCriterion("biz_order_id is not null");
			return this;
		}

		public Criteria andBizOrderIdEqualTo(Long value) {
			addCriterion("biz_order_id =", value, "bizOrderId");
			return this;
		}

		public Criteria andBizOrderIdNotEqualTo(Long value) {
			addCriterion("biz_order_id <>", value, "bizOrderId");
			return this;
		}

		public Criteria andBizOrderIdGreaterThan(Long value) {
			addCriterion("biz_order_id >", value, "bizOrderId");
			return this;
		}

		public Criteria andBizOrderIdGreaterThanOrEqualTo(Long value) {
			addCriterion("biz_order_id >=", value, "bizOrderId");
			return this;
		}

		public Criteria andBizOrderIdLessThan(Long value) {
			addCriterion("biz_order_id <", value, "bizOrderId");
			return this;
		}

		public Criteria andBizOrderIdLessThanOrEqualTo(Long value) {
			addCriterion("biz_order_id <=", value, "bizOrderId");
			return this;
		}

		public Criteria andBizOrderIdIn(List values) {
			addCriterion("biz_order_id in", values, "bizOrderId");
			return this;
		}

		public Criteria andBizOrderIdNotIn(List values) {
			addCriterion("biz_order_id not in", values, "bizOrderId");
			return this;
		}

		public Criteria andBizOrderIdBetween(Long value1, Long value2) {
			addCriterion("biz_order_id between", value1, value2, "bizOrderId");
			return this;
		}

		public Criteria andBizOrderIdNotBetween(Long value1, Long value2) {
			addCriterion("biz_order_id not between", value1, value2, "bizOrderId");
			return this;
		}

		public Criteria andOperIdIsNull() {
			addCriterion("oper_id is null");
			return this;
		}

		public Criteria andOperIdIsNotNull() {
			addCriterion("oper_id is not null");
			return this;
		}

		public Criteria andOperIdEqualTo(Integer value) {
			addCriterion("oper_id =", value, "operId");
			return this;
		}

		public Criteria andOperIdNotEqualTo(Integer value) {
			addCriterion("oper_id <>", value, "operId");
			return this;
		}

		public Criteria andOperIdGreaterThan(Integer value) {
			addCriterion("oper_id >", value, "operId");
			return this;
		}

		public Criteria andOperIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("oper_id >=", value, "operId");
			return this;
		}

		public Criteria andOperIdLessThan(Integer value) {
			addCriterion("oper_id <", value, "operId");
			return this;
		}

		public Criteria andOperIdLessThanOrEqualTo(Integer value) {
			addCriterion("oper_id <=", value, "operId");
			return this;
		}

		public Criteria andOperIdIn(List values) {
			addCriterion("oper_id in", values, "operId");
			return this;
		}

		public Criteria andOperIdNotIn(List values) {
			addCriterion("oper_id not in", values, "operId");
			return this;
		}

		public Criteria andOperIdBetween(Integer value1, Integer value2) {
			addCriterion("oper_id between", value1, value2, "operId");
			return this;
		}

		public Criteria andOperIdNotBetween(Integer value1, Integer value2) {
			addCriterion("oper_id not between", value1, value2, "operId");
			return this;
		}

		public Criteria andOperNameIsNull() {
			addCriterion("oper_name is null");
			return this;
		}

		public Criteria andOperNameIsNotNull() {
			addCriterion("oper_name is not null");
			return this;
		}

		public Criteria andOperNameEqualTo(String value) {
			addCriterion("oper_name =", value, "operName");
			return this;
		}

		public Criteria andOperNameNotEqualTo(String value) {
			addCriterion("oper_name <>", value, "operName");
			return this;
		}

		public Criteria andOperNameGreaterThan(String value) {
			addCriterion("oper_name >", value, "operName");
			return this;
		}

		public Criteria andOperNameGreaterThanOrEqualTo(String value) {
			addCriterion("oper_name >=", value, "operName");
			return this;
		}

		public Criteria andOperNameLessThan(String value) {
			addCriterion("oper_name <", value, "operName");
			return this;
		}

		public Criteria andOperNameLessThanOrEqualTo(String value) {
			addCriterion("oper_name <=", value, "operName");
			return this;
		}

		public Criteria andOperNameLike(String value) {
			addCriterion("oper_name like", value, "operName");
			return this;
		}

		public Criteria andOperNameNotLike(String value) {
			addCriterion("oper_name not like", value, "operName");
			return this;
		}

		public Criteria andOperNameIn(List values) {
			addCriterion("oper_name in", values, "operName");
			return this;
		}

		public Criteria andOperNameNotIn(List values) {
			addCriterion("oper_name not in", values, "operName");
			return this;
		}

		public Criteria andOperNameBetween(String value1, String value2) {
			addCriterion("oper_name between", value1, value2, "operName");
			return this;
		}

		public Criteria andOperNameNotBetween(String value1, String value2) {
			addCriterion("oper_name not between", value1, value2, "operName");
			return this;
		}

		public Criteria andGmtCreateIsNull() {
			addCriterion("gmt_create is null");
			return this;
		}

		public Criteria andGmtCreateIsNotNull() {
			addCriterion("gmt_create is not null");
			return this;
		}

		public Criteria andGmtCreateEqualTo(Date value) {
			addCriterionForJDBCDate("gmt_create =", value, "gmtCreate");
			return this;
		}

		public Criteria andGmtCreateNotEqualTo(Date value) {
			addCriterionForJDBCDate("gmt_create <>", value, "gmtCreate");
			return this;
		}

		public Criteria andGmtCreateGreaterThan(Date value) {
			addCriterionForJDBCDate("gmt_create >", value, "gmtCreate");
			return this;
		}

		public Criteria andGmtCreateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("gmt_create >=", value, "gmtCreate");
			return this;
		}

		public Criteria andGmtCreateLessThan(Date value) {
			addCriterionForJDBCDate("gmt_create <", value, "gmtCreate");
			return this;
		}

		public Criteria andGmtCreateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("gmt_create <=", value, "gmtCreate");
			return this;
		}

		public Criteria andGmtCreateIn(List values) {
			addCriterionForJDBCDate("gmt_create in", values, "gmtCreate");
			return this;
		}

		public Criteria andGmtCreateNotIn(List values) {
			addCriterionForJDBCDate("gmt_create not in", values, "gmtCreate");
			return this;
		}

		public Criteria andGmtCreateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("gmt_create between", value1, value2, "gmtCreate");
			return this;
		}

		public Criteria andGmtCreateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("gmt_create not between", value1, value2, "gmtCreate");
			return this;
		}

		public Criteria andGmtModifyIsNull() {
			addCriterion("gmt_modify is null");
			return this;
		}

		public Criteria andGmtModifyIsNotNull() {
			addCriterion("gmt_modify is not null");
			return this;
		}

		public Criteria andGmtModifyEqualTo(Date value) {
			addCriterionForJDBCDate("gmt_modify =", value, "gmtModify");
			return this;
		}

		public Criteria andGmtModifyNotEqualTo(Date value) {
			addCriterionForJDBCDate("gmt_modify <>", value, "gmtModify");
			return this;
		}

		public Criteria andGmtModifyGreaterThan(Date value) {
			addCriterionForJDBCDate("gmt_modify >", value, "gmtModify");
			return this;
		}

		public Criteria andGmtModifyGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("gmt_modify >=", value, "gmtModify");
			return this;
		}

		public Criteria andGmtModifyLessThan(Date value) {
			addCriterionForJDBCDate("gmt_modify <", value, "gmtModify");
			return this;
		}

		public Criteria andGmtModifyLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("gmt_modify <=", value, "gmtModify");
			return this;
		}

		public Criteria andGmtModifyIn(List values) {
			addCriterionForJDBCDate("gmt_modify in", values, "gmtModify");
			return this;
		}

		public Criteria andGmtModifyNotIn(List values) {
			addCriterionForJDBCDate("gmt_modify not in", values, "gmtModify");
			return this;
		}

		public Criteria andGmtModifyBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("gmt_modify between", value1, value2, "gmtModify");
			return this;
		}

		public Criteria andGmtModifyNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("gmt_modify not between", value1, value2, "gmtModify");
			return this;
		}

		public Criteria andErrorCodeIsNull() {
			addCriterion("error_code is null");
			return this;
		}

		public Criteria andErrorCodeIsNotNull() {
			addCriterion("error_code is not null");
			return this;
		}

		public Criteria andErrorCodeEqualTo(String value) {
			addCriterion("error_code =", value, "errorCode");
			return this;
		}

		public Criteria andErrorCodeNotEqualTo(String value) {
			addCriterion("error_code <>", value, "errorCode");
			return this;
		}

		public Criteria andErrorCodeGreaterThan(String value) {
			addCriterion("error_code >", value, "errorCode");
			return this;
		}

		public Criteria andErrorCodeGreaterThanOrEqualTo(String value) {
			addCriterion("error_code >=", value, "errorCode");
			return this;
		}

		public Criteria andErrorCodeLessThan(String value) {
			addCriterion("error_code <", value, "errorCode");
			return this;
		}

		public Criteria andErrorCodeLessThanOrEqualTo(String value) {
			addCriterion("error_code <=", value, "errorCode");
			return this;
		}

		public Criteria andErrorCodeLike(String value) {
			addCriterion("error_code like", value, "errorCode");
			return this;
		}

		public Criteria andErrorCodeNotLike(String value) {
			addCriterion("error_code not like", value, "errorCode");
			return this;
		}

		public Criteria andErrorCodeIn(List values) {
			addCriterion("error_code in", values, "errorCode");
			return this;
		}

		public Criteria andErrorCodeNotIn(List values) {
			addCriterion("error_code not in", values, "errorCode");
			return this;
		}

		public Criteria andErrorCodeBetween(String value1, String value2) {
			addCriterion("error_code between", value1, value2, "errorCode");
			return this;
		}

		public Criteria andErrorCodeNotBetween(String value1, String value2) {
			addCriterion("error_code not between", value1, value2, "errorCode");
			return this;
		}

		public Criteria andErrorMsgIsNull() {
			addCriterion("error_msg is null");
			return this;
		}

		public Criteria andErrorMsgIsNotNull() {
			addCriterion("error_msg is not null");
			return this;
		}

		public Criteria andErrorMsgEqualTo(String value) {
			addCriterion("error_msg =", value, "errorMsg");
			return this;
		}

		public Criteria andErrorMsgNotEqualTo(String value) {
			addCriterion("error_msg <>", value, "errorMsg");
			return this;
		}

		public Criteria andErrorMsgGreaterThan(String value) {
			addCriterion("error_msg >", value, "errorMsg");
			return this;
		}

		public Criteria andErrorMsgGreaterThanOrEqualTo(String value) {
			addCriterion("error_msg >=", value, "errorMsg");
			return this;
		}

		public Criteria andErrorMsgLessThan(String value) {
			addCriterion("error_msg <", value, "errorMsg");
			return this;
		}

		public Criteria andErrorMsgLessThanOrEqualTo(String value) {
			addCriterion("error_msg <=", value, "errorMsg");
			return this;
		}

		public Criteria andErrorMsgLike(String value) {
			addCriterion("error_msg like", value, "errorMsg");
			return this;
		}

		public Criteria andErrorMsgNotLike(String value) {
			addCriterion("error_msg not like", value, "errorMsg");
			return this;
		}

		public Criteria andErrorMsgIn(List values) {
			addCriterion("error_msg in", values, "errorMsg");
			return this;
		}

		public Criteria andErrorMsgNotIn(List values) {
			addCriterion("error_msg not in", values, "errorMsg");
			return this;
		}

		public Criteria andErrorMsgBetween(String value1, String value2) {
			addCriterion("error_msg between", value1, value2, "errorMsg");
			return this;
		}

		public Criteria andErrorMsgNotBetween(String value1, String value2) {
			addCriterion("error_msg not between", value1, value2, "errorMsg");
			return this;
		}

		public Criteria andLogTypeIsNull() {
			addCriterion("log_type is null");
			return this;
		}

		public Criteria andLogTypeIsNotNull() {
			addCriterion("log_type is not null");
			return this;
		}

		public Criteria andLogTypeEqualTo(Integer value) {
			addCriterion("log_type =", value, "logType");
			return this;
		}

		public Criteria andLogTypeNotEqualTo(Integer value) {
			addCriterion("log_type <>", value, "logType");
			return this;
		}

		public Criteria andLogTypeGreaterThan(Integer value) {
			addCriterion("log_type >", value, "logType");
			return this;
		}

		public Criteria andLogTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("log_type >=", value, "logType");
			return this;
		}

		public Criteria andLogTypeLessThan(Integer value) {
			addCriterion("log_type <", value, "logType");
			return this;
		}

		public Criteria andLogTypeLessThanOrEqualTo(Integer value) {
			addCriterion("log_type <=", value, "logType");
			return this;
		}

		public Criteria andLogTypeIn(List values) {
			addCriterion("log_type in", values, "logType");
			return this;
		}

		public Criteria andLogTypeNotIn(List values) {
			addCriterion("log_type not in", values, "logType");
			return this;
		}

		public Criteria andLogTypeBetween(Integer value1, Integer value2) {
			addCriterion("log_type between", value1, value2, "logType");
			return this;
		}

		public Criteria andLogTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("log_type not between", value1, value2, "logType");
			return this;
		}

		public Criteria andMemoIsNull() {
			addCriterion("memo is null");
			return this;
		}

		public Criteria andMemoIsNotNull() {
			addCriterion("memo is not null");
			return this;
		}

		public Criteria andMemoEqualTo(String value) {
			addCriterion("memo =", value, "memo");
			return this;
		}

		public Criteria andMemoNotEqualTo(String value) {
			addCriterion("memo <>", value, "memo");
			return this;
		}

		public Criteria andMemoGreaterThan(String value) {
			addCriterion("memo >", value, "memo");
			return this;
		}

		public Criteria andMemoGreaterThanOrEqualTo(String value) {
			addCriterion("memo >=", value, "memo");
			return this;
		}

		public Criteria andMemoLessThan(String value) {
			addCriterion("memo <", value, "memo");
			return this;
		}

		public Criteria andMemoLessThanOrEqualTo(String value) {
			addCriterion("memo <=", value, "memo");
			return this;
		}

		public Criteria andMemoLike(String value) {
			addCriterion("memo like", value, "memo");
			return this;
		}

		public Criteria andMemoNotLike(String value) {
			addCriterion("memo not like", value, "memo");
			return this;
		}

		public Criteria andMemoIn(List values) {
			addCriterion("memo in", values, "memo");
			return this;
		}

		public Criteria andMemoNotIn(List values) {
			addCriterion("memo not in", values, "memo");
			return this;
		}

		public Criteria andMemoBetween(String value1, String value2) {
			addCriterion("memo between", value1, value2, "memo");
			return this;
		}

		public Criteria andMemoNotBetween(String value1, String value2) {
			addCriterion("memo not between", value1, value2, "memo");
			return this;
		}
	}
}