package com.longan.biz.dataobject;

public class UserRoleRelation {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user_role_relation.id
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	private Integer id;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user_role_relation.user_id
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	private Long userId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user_role_relation.role_id
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	private Integer roleId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column user_role_relation.status
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	private Integer status;
	private String haveRole;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user_role_relation.id
	 * 
	 * @return the value of user_role_relation.id
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user_role_relation.id
	 * 
	 * @param id
	 *            the value for user_role_relation.id
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user_role_relation.user_id
	 * 
	 * @return the value of user_role_relation.user_id
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user_role_relation.user_id
	 * 
	 * @param userId
	 *            the value for user_role_relation.user_id
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user_role_relation.role_id
	 * 
	 * @return the value of user_role_relation.role_id
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user_role_relation.role_id
	 * 
	 * @param roleId
	 *            the value for user_role_relation.role_id
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column user_role_relation.status
	 * 
	 * @return the value of user_role_relation.status
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column user_role_relation.status
	 * 
	 * @param status
	 *            the value for user_role_relation.status
	 * 
	 * @abatorgenerated Thu Mar 06 15:12:58 CST 2014
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	public String getHaveRole() {
		return haveRole;
	}

	public void setHaveRole(String haveRole) {
		this.haveRole = haveRole;
	}

}